import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tareq Hasan",
  description: "Generated by Tareq",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* lg:px-48 md:px-20 */}
        <div className="fixed w-full top-0  ">
          <Navbar />
        </div>
        <div className=" lg:px-48 md:px-20 ">{children}</div>
        <div className=" w-full ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
